version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PGDATA: /data/postgres
    ports:
    - '${TYPEORM_PORT}:5432'
