name: Test CMS API

on:
  push:
    paths: [ '.github/**', 'package.json', 'lerna.json', 'packages/cms-api/*' ]
    branches: [ master ]
  pull_request:
    paths: [ '.github/**', 'package.json', 'lerna.json', 'packages/cms-api/*' ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn workspace cms-api install
      - run: yarn workspace cms-api test:unit
      - run: yarn workspace cms-api test:integration
