name: Test CMS admin client

on:
  push:
    paths: [ '.github/**', 'package.json', 'lerna.json', 'packages/cms-admin/*' ]
    branches: [ master ]
  pull_request:
    paths: [ '.github/**', 'package.json', 'lerna.json', 'packages/cms-admin/*' ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn workspace cms-admin install
      - run: yarn workspace cms-admin test
      - run: yarn workspace cms-admin build
